runtime: python39

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: ccprojectadmin@2021
  CLOUD_SQL_DATABASE_NAME: medicine
  CLOUD_SQL_CONNECTION_NAME: medicine-expiry-rmdr:us-central1:medicine-database-2021
  CLOUD_STORAGE_BUCKET: medicine-expiry-reminder

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /templates
  static_dir: template

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 50
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 10
